name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker run -it -e UNITTEST=1 -v $(PWD):$(PWD) -w $(PWD) "ktf:build" tools/docker/Dockerfile bash -c "make -j boot.iso"
